module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        inter: ["Inter", "sans-serif"],
        geist: ["Geist", "sans-serif"],
        newsreader: ["Newsreader", "serif"],
        "geist-mono": ["Geist Mono", "monospace"],
        lobster: ["var(--font-lobster)", "cursive"],
        justmeagaindownhere: ["JustMeAgainDownHere", "serif"],
        ptmono: ["PTMono", ...defaultTheme.fontFamily.mono],
        questrial: ["Questrial", "sans-serif"],
      },
      fontWeight: {
        thin: "50",
        hairline: "100",
        extralight: "200",
        light: "300",
        normal: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        extrabold: "800",
        black: "900",
      },
      fontSize: {
        xxs: "0.4rem",
        sm: "0.8rem",
        base: "1rem",
        xl: "1.25rem",
        "2xl": "1.563rem",
        "3xl": "1.953rem",
        "4xl": "2.441rem",
        "5xl": "3.052rem",
        "6xl": "3.815rem",
        "7xl": "4.768rem",
        "8xl": "5.960rem",
        "9xl": "7.450rem",
      },
    },
  },
  plugins: [],
};
